CREATE TABLE [src].[Eloqua_visitors]
(
[SK] [bigint] NULL,
[ETL__multi_query_value_for_audit] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[page] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pageSize] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_visitorId] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_createdAt] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-Browser-Type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-IPAddress] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-Total-Pages] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-Total-Time] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-Total-Visits] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-Name] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-Current-Visit-Length] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-Current-Total-Pages] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-FirstVisitDateAndTime] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-FirstPageInVisit] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-LastPageInVisit] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-LastVisitDateAndTime] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-TimeZoneOffsetMin] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-TimeZone] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-CountryFromIP] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-CompanyNameFromIP1] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-ISPFromIP] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-ProvinceFromIP] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-CityFromIP] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-LatitudeFromIP] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-LongitudeFromIP] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_externalId] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_currentStatus] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-HostName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-CompanyDNSName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_contactId] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-ZipCodeFromIP] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[elements_V-CountryName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
