CREATE SCHEMA [mdm]
AUTHORIZATION [dbo]
GO
GRANT ALTER ON SCHEMA:: [mdm] TO [db_apiETL]
GO
GRANT DELETE ON SCHEMA:: [mdm] TO [db_apiETL]
GO
GRANT EXECUTE ON SCHEMA:: [mdm] TO [db_apiETL]
GO
GRANT INSERT ON SCHEMA:: [mdm] TO [db_apiETL]
GO
GRANT SELECT ON SCHEMA:: [mdm] TO [db_apiETL]
GO
GRANT UPDATE ON SCHEMA:: [mdm] TO [db_apiETL]
GO
